app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Invtation/MainController.php
<?php

namespace App\Http\Controllers\Invitation;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class MainController extends Controller
{
    public function index()
    {
        return view('page.invitation.desktop.home.main');
    }
}

app/Http/Controllers/Invtation/TransactionController.php
<?php

namespace App\Http\Controllers\Invtation;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Traits\ReplyJson;
use App\Traits\InvitationView;

class TransactionController extends Controller
{
    use InvitationView, ReplyJson;
    public function index()
    {
        $tanggal = date('2022-03-20');
        return $this->render_view('transaction.main',compact('tanggal'));
        return view('page.invitation.desktop.transaction.main',compact('tanggal'));
    }
    public function modal_prokes()
    {
        return $this->render_view('transaction.modal_prokes');
    }
    public function show()
    {
        $tanggal = date('2022-03-20');
        return $this->render_view('transaction.show',compact('tanggal'));
    }
}

app/Http/Controllers/Web/MainController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class MainController extends Controller
{
    public function index()
    {
        return view('page.web.desktop.home.main');
    }
}

app/View/Components/InvitationLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class InvitationLayout extends Component
{
    public $title;
    public function __construct($title)
    {
        $this->title = $title;
    }
    public function render()
    {
        return view('theme.invitation.main');
    }
}

app/View/Components/MobileInvitationLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class MobileInvitationLayout extends Component
{
    public $title;
    public function __construct($title)
    {
        $this->title = $title;
    }
    public function render()
    {
        return view('theme.mobile_invitation.main');
    }
}

app/View/Components/MobileWebLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class MobileWebLayout extends Component
{
    public $title;
    public function __construct($title)
    {
        $this->title = $title;
    }
    public function render()
    {
        return view('theme.mobile_web.main');
    }
}

app/View/Components/OfficeLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class OfficeLayout extends Component
{
    public $title;
    public function __construct($title)
    {
        $this->title = $title;
    }
    public function render()
    {
        return view('theme.office.main');
    }
}

app/View/Components/WebInvitationLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class WebInvitationLayout extends Component
{
    public $title;
    public function __construct($title)
    {
        $this->title = $title;
    }
    public function render()
    {
        return view('theme.web_invitation.main');
    }
}

app/View/Components/WebLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class WebLayout extends Component
{
    public $title;
    public function __construct($title)
    {
        $this->title = $title;
    }
    public function render()
    {
        return view('theme.web.main');
    }
}

resources/views/page/invitation/desktop/home/main.blade.php
<x-web-invitation-layout title="Welcome">
    <!-- Content
    ============================================= -->
    <section id="content">
        <div class="content-wrap py-0">

            <div class="section parallax min-vh-100 dark m-0 border-0 d-flex" style="background-image: url('images/parallax/1.jpg');" data-bottom-top="background-position:0px 0px;" data-top-bottom="background-position:0px -300px;">
                <div class="vertical-middle">
                    <div class="container">

                        <div class="row col-mb-50">
                            <div class="col-sm-6 col-lg-3 text-center" data-animate="bounceIn">
                                <i class="i-plain i-xlarge mx-auto mb-0 icon-code"></i>
                                <div class="counter counter-large counter-lined"><span data-from="100" data-to="846" data-refresh-interval="50" data-speed="2000"></span>K+</div>
                                <h5>Lines of Codes</h5>
                            </div>

                            <div class="col-sm-6 col-lg-3 text-center" data-animate="bounceIn" data-delay="200">
                                <i class="i-plain i-xlarge mx-auto mb-0 icon-magic"></i>
                                <div class="counter counter-large counter-lined"><span data-from="3000" data-to="15360" data-refresh-interval="100" data-speed="2500"></span>+</div>
                                <h5>KBs of HTML Files</h5>
                            </div>

                            <div class="col-sm-6 col-lg-3 text-center" data-animate="bounceIn" data-delay="400">
                                <i class="i-plain i-xlarge mx-auto mb-0 icon-file-text"></i>
                                <div class="counter counter-large counter-lined"><span data-from="10" data-to="386" data-refresh-interval="25" data-speed="3500"></span>*</div>
                                <h5>No. of Templates</h5>
                            </div>

                            <div class="col-sm-6 col-lg-3 text-center" data-animate="bounceIn" data-delay="600">
                                <i class="i-plain i-xlarge mx-auto mb-0 icon-time"></i>
                                <div class="counter counter-large counter-lined"><span data-from="60" data-to="1200" data-refresh-interval="30" data-speed="2700"></span>+</div>
                                <h5>Hours of Coding</h5>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="section parallax min-vh-100 m-0 border-0 d-flex" style="background-image: url('images/parallax/home/11.jpg');" data-bottom-top="background-position:-200px -250px;" data-top-bottom="background-position:0px -400px;">
                <div class="vertical-middle">
                    <div class="container">

                        <div class="row">
                            <div class="col-md-5">
                                <div class="emphasis-title">
                                    <h2>Seriously Parallaxical</h2>
                                    <p class="lead topmargin-sm">Create beautiful unlimited full-screen parallax defined backgrounds to spell bound your visitors.</p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="row p-0 align-items-stretch">

                <div class="col-lg-4 dark col-padding overflow-hidden" style="background-color: #1abc9c;">
                    <div>
                        <h3 class="text-uppercase" style="font-weight: 600;">Why choose Us</h3>
                        <p style="line-height: 1.8;">Transform, agency working families thinkers who make change happen communities. Developing nations legal aid public sector our ambitions future aid The Elders economic security Rosa.</p>
                        <a href="#" class="button button-border button-light button-rounded text-uppercase m-0">Read More</a>
                        <i class="icon-bulb bgicon"></i>
                    </div>
                </div>

                <div class="col-lg-4 dark col-padding overflow-hidden" style="background-color: #34495e;">
                    <div>
                        <h3 class="text-uppercase" style="font-weight: 600;">Our Mission</h3>
                        <p style="line-height: 1.8;">Frontline respond, visionary collaborative cities advancement overcome injustice, UNHCR public-private partnerships cause. Giving, country educate rights-based approach; leverage disrupt solution.</p>
                        <a href="#" class="button button-border button-light button-rounded text-uppercase m-0">Read More</a>
                        <i class="icon-cog bgicon"></i>
                    </div>
                </div>

                <div class="col-lg-4 dark col-padding overflow-hidden" style="background-color: #e74c3c;">
                    <div>
                        <h3 class="text-uppercase" style="font-weight: 600;">What you get</h3>
                        <p style="line-height: 1.8;">Sustainability involvement fundraising campaign connect carbon rights, collaborative cities convener truth. Synthesize change lives treatment fluctuation participatory monitoring underprivileged equal.</p>
                        <a href="#" class="button button-border button-light button-rounded text-uppercase m-0">Read More</a>
                        <i class="icon-thumbs-up bgicon"></i>
                    </div>
                </div>

            </div>

            <div class="clear"></div>

            <div class="section m-0 border-0" style="background-image: url('images/parallax/3.jpg');">
                <div class="heading-block center border-bottom-0 mb-0">
                    <h2>"Everything is designed, but some things are designed well."</h2>
                </div>
            </div>

            <div class="section parallax min-vh-100 dark m-0 border-0 d-flex" style="background-image: url('images/parallax/home/10.jpg');"  data-bottom-top="background-position:0px 0px;" data-top-bottom="background-position:0px -300px;">
                <div class="vertical-middle">
                    <div class="container">

                        <div class="row align-items-center gutter-40 col-mb-50">
                            <div class="col-md-6">
                                <iframe src="https://player.vimeo.com/video/243244233?title=0&byline=0&portrait=0" width="640" height="360" allow="autoplay; fullscreen" allowfullscreen></iframe>
                            </div>

                            <div class="col-md-6">
                                <div class="emphasis-title">
                                    <h2>Embed Videos</h2>
                                    <p class="lead topmargin-sm">Show off your Vimeo &amp; Videos in style and with a perfect aspect ratio.</p>
                                </div>

                                <a href="#" class="button button-border button-rounded button-light button-large">Go to Vimeo</a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="section parallax dark m-0 border-0" style="padding: 150px 0; background-image: url('images/parallax/home/5.jpg');" data-bottom-top="background-position:0px -300px;" data-top-bottom="background-position:0px 0px;">
                <div class="container text-center">

                    <div class="emphasis-title">
                        <h2>Perfect tool for Customization</h2>
                        <p class="lead topmargin-sm">Create as much unique content as you want with this Template which has powerful &amp; optimized code.</p>
                    </div>

                    <a href="#" class="button button-border button-rounded button-light button-large">Start Browsing</a>
                    <a href="#" class="button button-rounded button-white button-light button-large">Buy Now</a>

                </div>
            </div>
        </div>
    </section>
</x-web-invitation-layout>

resources/views/page/invitation/desktop/transaction/main.blade.php
<x-invitation-layout title="Undangan Pernikahan : Eddy & Riri">
    <div class="gla_over" data-color="#D59696" data-opacity="0"></div>
    <a href="#gla_page" class="gla_top ti ti-angle-up gla_go"></a>
    <div class="gla_music_icon">
        <i class="ti ti-music" id="music_button"></i>
    </div>
    <div class="gla_music_icon_cont">
        <audio id="audio" loop>
            <source src="{{asset('music/source.mp3')}}" type="audio/mp3" />
        </audio>
    </div>
    <section id="gla_content" class="gla_content">
        <div id="content_list">
            <div class="gla_invitation_container" style="margin-top:-3%;">
                <div class="gla_invitation_i gla_invitation_ii gla_image_bck" data-image="{{asset('img/invitation/pink.png')}}">
                    {{-- <p><img src="{{asset('img/invitation/save_the_date_bl.gif')}}" alt="" height="200"></p> --}}
                    <h4 style="font-size:50px;margin-top:10%">Engagement</h4>
                    <h4 style="font-size:50px;margin-top:10%">Ceremony</h4>
                    <h3>
                        Rianasari
                        <br>
                        &
                        <br>
                        Eddy Mardiwan
                    </h3>
                    <h4 style="font-size:50px;">{{Carbon\Carbon::parse($tanggal)->isoFormat('dddd')}}</h4>
                    <h4 style="font-size:39px;margin-top:10%;">{{Carbon\Carbon::parse($tanggal)->isoFormat('D MMMM Y')}}</h4>
                    {{-- <h4 style="font-size:20px;">Restaurant Bunga Rampai</h4> --}}
                    <br>
                    <button type="button" class="btn medium btn_border" onclick="handle_open_modal('{{route('invitation.transaction.modal_prokes')}}','#Modal','#contentModal');">Buka Undangan</button>
                    {{-- <h4 style="font-size:16px;">
                        Jl. Teuku Cik Ditiro No.35, RT.10/RW.5, Menteng, Kec. Menteng, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10310
                    </h4> --}}
                </div>
            </div>
        </div>
        <div id="content_invitation"></div>
    </section>
    @section('custom_js')
        <script src="{{asset('glanz/js/glanz_library.js')}}"></script> 
        <script src="{{asset('glanz/js/glanz_script.js')}}"></script>
        <script type="text/javascript">
            main_content('content_list');
            $(".gla_music_icon").hide();
            // function confirm_open_invitation(){
            //     $("#invitation").hide();
            //     $(".gla_music_icon").show();
            //     $(".gla_invitation_container").hide();
            //     // audio.play();
            //     $("#slider").show();
            //     $("#list_result").show();
            //     $("#ProkesModal").hide();
            //     $('.modal-backdrop').remove();
            // }
            // $(".gla_music_icon").click(function(){
            //     $('#audio').on('pause', function() {
            //         if (audio.paused) {
            //             audio.play();
            //             $('button.toggle-stream').attr('data-icon','s');
            //         }   
            //         else {
            //             audio.pause();
            //             $('button.toggle-stream').attr('data-icon','p');
            //         }
            //     });
            // });
        </script>
    @endsection
</x-invitation-layout>

resources/views/page/invitation/desktop/transaction/modal_prokes.blade.php
<div class="top-border">
    <img width="40px" src="{{asset('img/prokes/head.png')}}">
</div>
<div class="bottom-border"></div>
<div class="bottom-sign">
    <h3>-E &amp; R-</h3>
</div>
<div class="body p-4" style="border-radius: 7px;overflow: hidden">
    <div style="text-align: center;padding-top: 10px;">
        <h5>Informasi Protokol Kesehatan</h5>
        <p>Acara ini akan dilaksanakan dengan menerapkan protokol kesehatan.</p>
        <ul style="margin-top:20px;">
            <li>
                <div class="item">
                    <img src="{{asset('img/prokes/1.png')}}" alt="">
                    <h4>Memakai Masker</h4>
                </div>
            </li>
            <li>
                <div class="item">
                    <img src="{{asset('img/prokes/2.png')}}" alt="">
                    <h4>Menjaga Jarak</h4>
                </div>
            </li>
            <li>
                <div class="item">
                    <img src="{{asset('img/prokes/3.png')}}" alt="">
                    <h4>Mencuci Tangan</h4>
                </div>
            </li>
        </ul>
    </div>
    <div class="prokes-footer">
        <button type="button" data-dismiss="modal" class="btn medium btn_border" style="margin-top:10%;" onclick="load_invitation('{{route('invitation.transaction.show')}}');">Baik, Saya Mengerti</button>
    </div>
</div>

resources/views/page/web/desktop/home/main.blade.php
<x-web-layout title="Welcome">
    <!-- Content
    ============================================= -->
    <section id="content">
        <div class="content-wrap py-0">

            <div class="section parallax min-vh-100 dark m-0 border-0 d-flex" style="background-image: url('images/parallax/1.jpg');" data-bottom-top="background-position:0px 0px;" data-top-bottom="background-position:0px -300px;">
                <div class="vertical-middle">
                    <div class="container">

                        <div class="row col-mb-50">
                            <div class="col-sm-6 col-lg-3 text-center" data-animate="bounceIn">
                                <i class="i-plain i-xlarge mx-auto mb-0 icon-code"></i>
                                <div class="counter counter-large counter-lined"><span data-from="100" data-to="846" data-refresh-interval="50" data-speed="2000"></span>K+</div>
                                <h5>Lines of Codes</h5>
                            </div>

                            <div class="col-sm-6 col-lg-3 text-center" data-animate="bounceIn" data-delay="200">
                                <i class="i-plain i-xlarge mx-auto mb-0 icon-magic"></i>
                                <div class="counter counter-large counter-lined"><span data-from="3000" data-to="15360" data-refresh-interval="100" data-speed="2500"></span>+</div>
                                <h5>KBs of HTML Files</h5>
                            </div>

                            <div class="col-sm-6 col-lg-3 text-center" data-animate="bounceIn" data-delay="400">
                                <i class="i-plain i-xlarge mx-auto mb-0 icon-file-text"></i>
                                <div class="counter counter-large counter-lined"><span data-from="10" data-to="386" data-refresh-interval="25" data-speed="3500"></span>*</div>
                                <h5>No. of Templates</h5>
                            </div>

                            <div class="col-sm-6 col-lg-3 text-center" data-animate="bounceIn" data-delay="600">
                                <i class="i-plain i-xlarge mx-auto mb-0 icon-time"></i>
                                <div class="counter counter-large counter-lined"><span data-from="60" data-to="1200" data-refresh-interval="30" data-speed="2700"></span>+</div>
                                <h5>Hours of Coding</h5>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="section parallax min-vh-100 m-0 border-0 d-flex" style="background-image: url('images/parallax/home/11.jpg');" data-bottom-top="background-position:-200px -250px;" data-top-bottom="background-position:0px -400px;">
                <div class="vertical-middle">
                    <div class="container">

                        <div class="row">
                            <div class="col-md-5">
                                <div class="emphasis-title">
                                    <h2>Seriously Parallaxical</h2>
                                    <p class="lead topmargin-sm">Create beautiful unlimited full-screen parallax defined backgrounds to spell bound your visitors.</p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="row p-0 align-items-stretch">

                <div class="col-lg-4 dark col-padding overflow-hidden" style="background-color: #1abc9c;">
                    <div>
                        <h3 class="text-uppercase" style="font-weight: 600;">Why choose Us</h3>
                        <p style="line-height: 1.8;">Transform, agency working families thinkers who make change happen communities. Developing nations legal aid public sector our ambitions future aid The Elders economic security Rosa.</p>
                        <a href="#" class="button button-border button-light button-rounded text-uppercase m-0">Read More</a>
                        <i class="icon-bulb bgicon"></i>
                    </div>
                </div>

                <div class="col-lg-4 dark col-padding overflow-hidden" style="background-color: #34495e;">
                    <div>
                        <h3 class="text-uppercase" style="font-weight: 600;">Our Mission</h3>
                        <p style="line-height: 1.8;">Frontline respond, visionary collaborative cities advancement overcome injustice, UNHCR public-private partnerships cause. Giving, country educate rights-based approach; leverage disrupt solution.</p>
                        <a href="#" class="button button-border button-light button-rounded text-uppercase m-0">Read More</a>
                        <i class="icon-cog bgicon"></i>
                    </div>
                </div>

                <div class="col-lg-4 dark col-padding overflow-hidden" style="background-color: #e74c3c;">
                    <div>
                        <h3 class="text-uppercase" style="font-weight: 600;">What you get</h3>
                        <p style="line-height: 1.8;">Sustainability involvement fundraising campaign connect carbon rights, collaborative cities convener truth. Synthesize change lives treatment fluctuation participatory monitoring underprivileged equal.</p>
                        <a href="#" class="button button-border button-light button-rounded text-uppercase m-0">Read More</a>
                        <i class="icon-thumbs-up bgicon"></i>
                    </div>
                </div>

            </div>

            <div class="clear"></div>

            <div class="section m-0 border-0" style="background-image: url('images/parallax/3.jpg');">
                <div class="heading-block center border-bottom-0 mb-0">
                    <h2>"Everything is designed, but some things are designed well."</h2>
                </div>
            </div>

            <div class="section parallax min-vh-100 dark m-0 border-0 d-flex" style="background-image: url('images/parallax/home/10.jpg');"  data-bottom-top="background-position:0px 0px;" data-top-bottom="background-position:0px -300px;">
                <div class="vertical-middle">
                    <div class="container">

                        <div class="row align-items-center gutter-40 col-mb-50">
                            <div class="col-md-6">
                                <iframe src="https://player.vimeo.com/video/243244233?title=0&byline=0&portrait=0" width="640" height="360" allow="autoplay; fullscreen" allowfullscreen></iframe>
                            </div>

                            <div class="col-md-6">
                                <div class="emphasis-title">
                                    <h2>Embed Videos</h2>
                                    <p class="lead topmargin-sm">Show off your Vimeo &amp; Videos in style and with a perfect aspect ratio.</p>
                                </div>

                                <a href="#" class="button button-border button-rounded button-light button-large">Go to Vimeo</a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="section parallax dark m-0 border-0" style="padding: 150px 0; background-image: url('images/parallax/home/5.jpg');" data-bottom-top="background-position:0px -300px;" data-top-bottom="background-position:0px 0px;">
                <div class="container text-center">

                    <div class="emphasis-title">
                        <h2>Perfect tool for Customization</h2>
                        <p class="lead topmargin-sm">Create as much unique content as you want with this Template which has powerful &amp; optimized code.</p>
                    </div>

                    <a href="#" class="button button-border button-rounded button-light button-large">Start Browsing</a>
                    <a href="#" class="button button-rounded button-white button-light button-large">Buy Now</a>

                </div>
            </div>
        </div>
    </section>
</x-web-layout>

resources/views/theme/invitation/head.blade.php
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{$title}}</title>
    <!-- Favicon -->
    <link rel="icon" href="images/favicon.ico" type="image/x-icon">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    
    <!-- Library CSS -->
    <link href="{{asset('glanz/css/glanz_library.css')}}" rel="stylesheet">
    
    <!-- Icons CSS -->
    <link href="{{asset('glanz/fonts/themify-icons.css')}}" rel="stylesheet">
    
    <!-- Theme CSS -->
    <link href="{{asset('glanz/css/glanz_style.css')}}" rel="stylesheet">
    
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Dosis:300,400,600,700%7COpen+Sans:300,400,700%7CPlayfair+Display:400,400i,700,700i" rel="stylesheet">
    
    <!-- Other Fonts -->
    <link href="{{asset('glanz/fonts/marsha/stylesheet.css')}}" rel="stylesheet">
    <link href="{{asset('css/invitation.css')}}" rel="stylesheet">
</head>

resources/views/theme/invitation/js.blade.php
<script src="{{asset('glanz/js/jquery-1.12.4.min.js')}}"></script> 
<!-- Library JS -->
{{-- <script src="{{asset('glanz/js/glanz_library.js')}}"></script>  --}}

<!-- Theme JS -->
{{-- <script src="{{asset('glanz/js/glanz_script.js')}}"></script> --}}
<script src="{{asset('js/toastr.js')}}"></script>
<script src="{{asset('js/method.js')}}"></script>

resources/views/theme/invitation/main.blade.php
<!DOCTYPE html>
<html lang="en">
    @include('theme.invitation.head')
    <body class="gla_middle_titles">
        <div class="gla_page" id="gla_page">
            <!-- Page -->
            {{-- <div class="gla_page gla_image_bck" data-image="http://placehold.it/1400x800" data-color="#f2f2f2" id="gla_page" > --}}
            <!-- Content -->
            {{$slot}}
            <!-- Content End -->
            <!-- Page End -->
            <!-- JQuery -->
        </div>
        @include('theme.invitation.modal')
        @include('theme.invitation.js')
        {{-- <div id="music"><embed src="{{asset('music/source.mp3')}}" autostart=true loop=true></div> --}}
        @yield('custom_js')
    </body>
</html>

resources/views/theme/invitation/modal.blade.php
<div class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false" id="Modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content" style="width: 400px">
            <div id="contentModal"></div>
            {{-- <div class="modal-body" style="border-radius: 7px;overflow: hidden;">
                <h3 class="text-center">Informasi Protokol Kesehatan</h3>
                <h4 class="text-center" style="font-size:16px;">Acara ini akan dilaksanakan dengan menerapkan protokol kesehatan.</h4>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-4">
                            <img src="{{asset('img/prokes/1.png')}}" style="width:20%">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <a class="btn medium btn_border" href="javascript:;" data-toggle="modal" data-target="#ProkesModal">Baik, Saya Mengerti</a>
                        </div>
                    </div>
                </div>
            </div> --}}
        </div>
    </div>
</div>

resources/views/theme/mobile_invitation/head.blade.php
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover" />
    <title>{{$title}}</title>
    <link rel="stylesheet" type="text/css" href="{{asset('azures/styles/bootstrap.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('azures/styles/style.css')}}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Comforter&family=Grand+Hotel&family=Nanum+Myeongjo:wght@400;700;800&family=Pinyon+Script&family=Rochester&family=Satisfy&family=Sofia&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{asset('azures/fonts/css/fontawesome-all.min.css')}}">    
    <link rel="manifest" href="{{asset('azures/_manifest.json')}}" data-pwa-version="set_in_manifest_and_pwa_js">
    <link rel="apple-touch-icon" sizes="180x180" href="app/icons/icon-192x192.png">
    <link rel="stylesheet" class="page-highlight" type="text/css" href="{{asset('azures/styles/highlights/highlight_dark.css')}}">
</head>

resources/views/theme/mobile_invitation/js.blade.php
<script type="text/javascript" src="{{asset('js/jquery.min.js')}}"></script>
<script type="text/javascript" src="{{asset('azures/scripts/bootstrap.min.js')}}"></script>
<script type="text/javascript" src="{{asset('azures/scripts/custom.js')}}"></script>

resources/views/theme/mobile_invitation/main.blade.php
<!DOCTYPE HTML>
<html lang="en">
    @include('theme.mobile_invitation.head')
<body class="theme-light" data-highlight="highlight-pink2">
<div id="preloader"><div class="spinner-border color-highlight" role="status"></div></div>
<div id="page">
    {{$slot}}
</div>
@include('theme.mobile_invitation.js')
@yield('custom_js')
</body>
</html>